### ISSUE TITLE
网站聊天没回应，但dify日志能看到回应

### ISSUE THREAD

**Issue by dinggithub** [langgenius/webapp-conversation#10]
在vercel部署的网站聊天经常没回应，但在dify的日志里却能看到生成的对话，不知道哪里出问题了。vercel的log如下：
![image](https://github.com/langgenius/webapp-conversation/assets/16711606/dfc8e479-3d62-4f78-82ae-39add1712dec)
RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at CanonicalizeLocaleList (/var/task/.next/server/chunks/183.js:60105:17)
    at match (/var/task/.next/server/chunks/183.js:60365:108)
    at getLocaleOnServer (/var/task/.next/server/app/page.js:359:63)
    at LocaleLayout (/var/task/.next/server/app/page.js:373:20)
    at X (/var/task/.next/server/chunks/183.js:61941:13)
    at Na (/var/task/.next/server/chunks/183.js:62109:21)
    at Array.toJSON (/var/task/.next/server/chunks/183.js:61869:20)
    at stringify (<anonymous>)
    at da (/var/task/.next/server/chunks/183.js:61383:9)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2702072224'
}

**Comment by iamjoel** [comment]
Pull the latest code and reinstall dependencies to see if the issue still exists. It may be due to response timeout. Previously, the issue was caused by returning in block format, but now it supports returning in streaming format.

**Comment by iamjoel** [comment]
Pull the latest code and reinstall dependencies to see if the issue still exists. It may be due to response timeout. Previously, the issue was caused by returning in block format, but now it supports returning in streaming format.
