### ISSUE TITLE
Docker deployed，when APP is running， the  error reporting on background

### ISSUE THREAD

**Issue by surfboy2000** [langgenius/webapp-conversation#11]
RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at CanonicalizeLocaleList (/app/.next/server/chunks/757.js:60105:17)
    at match (/app/.next/server/chunks/757.js:60365:108)
    at getLocaleOnServer (/app/.next/server/app/page.js:359:63)
    at LocaleLayout (/app/.next/server/app/page.js:373:20)
    at X (/app/.next/server/chunks/757.js:61941:13)
    at Na (/app/.next/server/chunks/757.js:62109:21)
    at Array.toJSON (/app/.next/server/chunks/757.js:61869:20)
    at stringify (<anonymous>)
    at da (/app/.next/server/chunks/757.js:61383:9)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '4288037568'

**Comment by surfboy2000** [comment]
已经解决，api 配置问题

**Comment by codeloved** [comment]
哪里api配置问题呀，我也出现了这个问题

**Comment by devyujie** [comment]
解决了吗

**Comment by tangdw** [comment]
![Image](https://github.com/user-attachments/assets/96f46246-a69c-4def-9ca7-cb404d347de0)
