### ISSUE TITLE
 Bot Replies Not Displaying

### ISSUE THREAD

**Issue by fitquick** [langgenius/webapp-conversation#57]
When deploying on Vercel, there is no reply from the bot. When I reload, the reply is displayed, and the following error appears in Vercel's logs:

```error - TypeError: This ReadableStream did not return bytes.
    at consumeUint8ArrayReadableStream (/var/task/node_modules/next/dist/compiled/edge-runtime/index.js:1:15045)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendResponse (/var/task/node_modules/next/dist/server/send-response.js:42:34)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:968:25)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/var/task/node_modules/next/dist/server/base-server.js:1159:28)
    at async /var/task/node_modules/next/dist/server/response-cache/index.js:99:36```

**Comment by arshia-shakudo** [comment]
Have you found a way around this?

**Comment by Qwen-7052** [comment]
“internal server error

**Comment by Qwen-7052** [comment]
> 你找到解决这个问题的方法了吗？
“internal server error
我是刚刚接触这些，不知怎么解决？
